# Generated by Django 6.0.4 on 2026-04-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='portfolioURL',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
