# Generated by Django 6.0.4 on 2026-04-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_artistprofile_portfoliourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='tags',
            field=models.ManyToManyField(related_name='artist', to='core.tag'),
        ),
    ]
