# Generated by Django 6.0.4 on 2026-04-13 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0001_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_orders', to='users.artistprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='commissions.order'),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='commissions.order'),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='users.artistprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commissions.proposal'),
        ),
        migrations.AddField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='tags',
            field=models.ManyToManyField(related_name='requests', to='core.tag'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='commissions.request'),
        ),
        migrations.AddField(
            model_name='order',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commissions.request'),
        ),
        migrations.AddField(
            model_name='requestimage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='commissions.request'),
        ),
        migrations.AddField(
            model_name='review',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.artistprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commissions.order'),
        ),
        migrations.AddField(
            model_name='submission',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='commissions.order'),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commissions.submission'),
        ),
        migrations.AddField(
            model_name='submissionreview',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionreview',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='commissions.submission'),
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('request', 'artist')},
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('order', 'version')},
        ),
    ]
