# Generated by Django 6.0.4 on 2026-04-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfile',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='requestimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='orderfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='order_files/'),
        ),
        migrations.AddField(
            model_name='requestimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='request_images/'),
        ),
    ]
